### ISSUE TITLE
Scope parens as `punctuation.definition`?

### ISSUE THREAD

**Issue by Thom1729** [SublimeText/PackageDev#143]
Parentheses are currently scoped as `keyword.control.group`. Arguably, they should instead be scoped as `punctuation.definition` or `punctuation.section`.

The current scoping impair legibility in the default Mariana theme. Now:

![image](https://user-images.githubusercontent.com/16958499/30487922-dd04cd98-9a02-11e7-9e59-2ea06cf906d2.png)

With parens scoped as `punctuation.definition`:

![image](https://user-images.githubusercontent.com/16958499/30487967-fb67f1de-9a02-11e7-9371-4f15169d5f0c.png)

**Comment by FichteFoll** [comment]
I wonder about this. Most color schemes by default do not color punctuation scopes and arguably parens are very important in regular expressions, being the indicator for basically anything that's not a literal or a character set.

I could probably assign both scopes though, so that punctuation will win, if it is defined.
