### ISSUE TITLE
No copy setting link for nested settings

### ISSUE THREAD

**Issue by AmjadHD** [SublimeText/PackageDev#175]
The copy setting link doesn't show up for nested setting though it works well for simple ones, hope you fix it soon.
__NB__: __the package in the example (Sublime Linter) does provide side by side settings.__

![not_working](https://user-images.githubusercontent.com/33235928/33379914-aefe1e0c-d519-11e7-809e-49ed33f82681.png)

**Comment by FichteFoll** [comment]
Note that nested settings (or mappings in general) are largely unsupported due to their arbitrary nature, mostly for completions though. The copy link should show up regardless and I'm surprised there isn't even anything in the console.

By the way, SublimeLinter will restructure its settings with its next major release (4.0.0) and remove the default and user keys.

**Comment by FichteFoll** [comment]
I'll close this in favor of the more clear #157 and #178.
