### ISSUE TITLE
Noticeable lag scrolling default settings with custom font

### ISSUE THREAD

**Issue by KevinSjoberg** [SublimeText/PackageDev#191]
Having `PackageDev` installed, I get stutter/lag while scrolling through the default settings using either `Operator Mono SSm` or `PragmataPro Mono` as my font. Switching to `Menlo` will make scrolling fluent again. Disabling `PackageDev` fix the issue, so I'm pretty sure it's what causing the trouble.

Any ideas why this is happening?

**Comment by FichteFoll** [comment]
I suspect it's the pencil glyph we use as the clickable "edit this" button. It appears that your font might not have he glyph and whatever st or your OS does to resolve the glyph and draw it takes an unreasonable amount of time.

What os are you on?

**Comment by KevinSjoberg** [comment]
@FichteFoll I'm running `Mac OS, version 10.13.5 (17F77)`.

**Comment by FichteFoll** [comment]
If it renders fine in the view itself, it may be an issue with phantoms, since that's where the glyph is rendered in. I'm not at a computer right now, but that's the only thing I can imagine happening.

**Comment by keith-hall** [comment]
It'd be great if we could identify a way to replicate this with a free font, so that we could investigate locally. In the mean time, @KevinSjoberg, perhaps you could edit https://github.com/SublimeText/PackageDev/blob/da40c753d66c628b9e7d232a5a670f90e0f478a9/plugins_/settings/__init__.py#L250 with https://packagecontrol.io/packages/PackageResourceViewer to change the glyph to a simple letter, and see if that makes any difference in scrolling performance for you with those fonts.

**Comment by FichteFoll** [comment]
@KevinSjoberg were you able to do what @keith-hall suggested?

**Comment by KevinSjoberg** [comment]
@FichteFoll I'll try this out later today.

**Comment by KevinSjoberg** [comment]
@FichteFoll didn't make a difference, changing the theme did. I'd assume it was the culprit all along.

**Comment by FichteFoll** [comment]
Thanks for checking. I'll consider this not to be an issue of PD, then.
