### ISSUE TITLE
[Question] any plans to add support for .sublime-options file

### ISSUE THREAD

**Issue by thecodechef** [SublimeText/PackageDev#208]
#### Wondering about Sublime Options file?
  I was looking at the Unofficial docs recently and came across something
  I've never seen before. A [Sublime Options][sublime-options-docs] file to give sublime-text custom 
  env variables and I was wondering if this is an actually a thing and if it is then are planning to add 
  support for in `package-dev` which by the way kinda like the `.tm_properties` file

#### And another Thing?
   when i was looking at the [TextMate 2.0][multiple-choice-docs] Documentation
   I came across `${1|choice 1,...,choice 2|}` which gives snippets a multiple choice syntax
   that i would love to have in sublime text so my second question is any plans to add this to ether 
   `sublime-text-3` or `package-dev`

[sublime-options-docs]: http://docs.sublimetext.info/en/latest/extensibility/snippets.html#environment-variables
[multiple-choice-docs]: https://macromates.com/textmate/manual/snippets#multiple-choice
@wbond

**Comment by FichteFoll** [comment]
Sublime Options file aren't a thing that exist. The unofficial docs are wrong about that.
Maybe they were a thing i ST1 days but they haven't existed ever since I started using ST many years ago.

The mentioned feature still exists, however, although under the name of `.tmPreferences` and we refer to those as metadata (because they don't have an official name). See http://docs.sublimetext.info/en/latest/reference/metadata.html#shell-variables-child-of-settings.

**Comment by thecodechef** [comment]
ok thank you @FichteFoll for being quick to answer my first question, 
but I would also like to have an answer to my second question as well

**Comment by FichteFoll** [comment]
I don't see how I could answer the second question. I'm not aware of such a feature in ST and am in no position to add it. If it is added, PackageDev will certainly be updated to support this, however.
