### ISSUE TITLE
[sublime-syntax] No regex syntax highlighting in double-quoted strings

### ISSUE THREAD

**Issue by AmjadHD** [SublimeText/PackageDev#314]
Unlike single-quoted and unquoted strings in contexts where a regex is expected, syntax highlighting is not provided for double-quoted strings.
![image](https://user-images.githubusercontent.com/33235928/99197197-35209100-2791-11eb-877b-9335cbd2224e.png)
![image](https://user-images.githubusercontent.com/33235928/99197204-3e116280-2791-11eb-9e8d-74f917227659.png)

**Comment by FichteFoll** [comment]
This is a concious choice, because double-quoted strings inside YAML require an escape of the backslash character, which is *heavily* used in regular expressions, leading to the string becoming almost unreadable if defined correctly. This is also why your double-quoted example is not equal to the single-quoted one, as all backslashes would require another backslash to escape them.

Because such expressions would be a nightmare to read (JSON says hello), YAML has single-quoted strings that do *not* suffer from this problem, since their only escape sequence is a doubled single quote (`''`), and it would require basically a rewrite of the regular expression syntax definition that matches `\\<any>` sequences instead of `\<any>`, this is not feasible to support in my eyes. The current lack of highlighting should indicated that double-quoted strings are sub-optimal.
