### ISSUE TITLE
3.2.17 not tagged for ST4

### ISSUE THREAD

**Issue by michaelblyons** [SublimeText/PackageDev#321]
If 3.2.17 is forward-compatible, can it be tagged for ST4 release? Right now it's just `st3-v`-prefixed.

Also looking forward to 3.3.0. 😜

**Comment by FichteFoll** [comment]
I intended to release 3.2.17 and 3.3 simultaneously or at least within a short time frame, since 3.3 was mostly the same except for some new features (completions) that are only available for ST4 builds. After having hinted to work on this so many times over the last months and despite making quite some progress towards the release, I still can't promise when I'll finally be able to put that out, so you're probably right in that I should indeed make a 3.2.17 for ST4.

I screwed up the release message for 3.2.17 and need to make a 3.2.18 anyway.

**Comment by FichteFoll** [comment]
I tagged 3.2.18 for both the ST3 and ST4 release branch, so they should be out soon.
