### ISSUE TITLE
"gutter_foreground_highlight" value is not highlighted

### ISSUE THREAD

**Issue by AmjadHD** [SublimeText/PackageDev#338]
![image](https://user-images.githubusercontent.com/33235928/106962336-41d4d580-673f-11eb-935e-5958e45caa20.png)
ST3
PD: 3.2.18

**Comment by Ultra-Instinct-05** [comment]
This is already fixed by this commit https://github.com/SublimeText/PackageDev/pull/331/commits/1f19441dd831937c073e9b4291b4bed13e1fa12d (so may need to just cherry pick this commit to the ST3 branch)
![image](https://user-images.githubusercontent.com/34304644/106987843-568f8880-6794-11eb-9ed1-64455e505058.png)

Though note that `gutter_foreground_highlight` is ST 4050+ only (https://www.sublimetext.com/docs/color_schemes.html#global_settings-gutter:ver-dev) so it could be highlighted but it won't work in ST3

**Comment by FichteFoll** [comment]
Oh, I forgot this was for the ST3 branch. Since `gutter_foreground_highlight` is ST4-only, I'm not going to backport it.

**Comment by AmjadHD** [comment]
I guess you should reopen this until 3.3.2 is released.
