### ISSUE TITLE
pop: true completion should be pop: 1 in version: 2 syntaxes

### ISSUE THREAD

**Issue by keith-hall** [SublimeText/PackageDev#354]
PackageDev currently always offers a completion of `pop: true`, but when the `sublime-syntax` file specifies `version: 2`, `pop: 1` is preferred, so it would be nice if PackageDev would check the version and offer the relevant default pop value based on that :)

**Comment by Ultra-Instinct-05** [comment]
I guess, even with `version: 2`, we should not impose `pop: 1`. Maybe after `pop: | <- caret`, we could present an additional AC of `true` & 1, with default to 1 ? We could get even advanced and have 1 selected with an ability to increment if you press <kbd>up/down</kbd> (since `pop` supports knocking off arbitrary no. of contexts off the stack now in ST4)
