### ISSUE TITLE
What is this `confirm` attribute ?

### ISSUE THREAD

**Issue by AmjadHD** [SublimeText/PackageDev#360]
https://github.com/SublimeText/PackageDev/blob/35a68969f94459d38341ea373ab2e583e60d8cda/Package/Sublime%20Text%20Theme/Completions/Attributes.sublime-completions#L140

**Comment by FichteFoll** [comment]
Supposedly added in https://github.com/SublimeText/PackageDev/commit/04c6dad49f9b82be5392b0d0122dd4940112af5c#diff-ad52c484496e151c817e70a5eba4c0761ca4c4679a45dfffcde87d4d76b571e4R19, which I most likely sourced from the syntax definition. I cannot find the attribute mentioned in the documentation, nor used in the default theme, so it is most likely an error.

@deathaxe do you happen to know anything about it? My expertise on themes is very limited. Otherwise I'll just remove it for the next release.

**Comment by deathaxe** [comment]
That's part of Sublime Merge themes. It belongs to the hazardous buttons such as the "Stage" buttons. The "confirm" state is what is activated when clicking the first time and causes them to turn red.

**Comment by FichteFoll** [comment]
Thanks. We'll need to group that in the syntax definition and add a comment to prevent confusion in the future. I'll use this issue as  a reminder for that.
