### ISSUE TITLE
feature request: command to auto generate syntax tests based on code in syntax test file

### ISSUE THREAD

**Issue by jcberquist** [SublimeText/PackageDev#71]
I am just throwing this out there, as I am not sure about the amount of work it would involve. (I figured you would have a better idea about how much work it would be.) In the abstract at least I think it would very helpful to have a command that could walk over a line of code in a syntax test file and generate syntax tests for that code based on the scope names it currently has. This would be a time saver when tweaking syntax scopes in a `.sublime-syntax` file. So for example you would go from before:

```
<!-- SYNTAX TEST "HTML.sublime-syntax" -->
<html>
```

to after:

```
<!-- SYNTAX TEST "HTML.sublime-syntax" -->
<html>
<!-- <- text.html.basic meta.tag.structure.any.html punctuation.definition.tag.begin.html -->
 <!-- <- entity.name.tag.structure.any.html -punctuation.definition.tag.begin.html -->
<!-- ^ punctuation.definition.tag.end.html -entity.name.tag.structure.any.html -->
```

or some form of the above. I figure it would add a test wherever the set of scope names changed on the line. What do you think?

**Comment by FichteFoll** [comment]
Thanks for the suggestion. That definitely sounds doable, assuming we don't do too much guessing or configuration, which would complicate things.

I'd have to think about how much specific the scope selectors need to be when the scope name changes. Maybe you can think of some more examples or rules?

**Comment by jcberquist** [comment]
Thanks for considering this! I have a bunch of syntax tests that don't test for scope endings/subtractions, which bit me recently; I need to go back and update them and a command like this would save me a lot of grunt work time.

I don't know that I have some rules to share, but my naive thought is that I would start each line with a list of all scopes present there as a baseline. I don't think I would be inclined to look outside the line, as a scope subtraction can easily be added manually if the test needs to ensure that some particular scope is not present, and that seems like it could get really complicated. (This line could be removed if it is not needed, but it would indicate which scopes were present at the start of the line.) Then I would definitely want the full scope names of any scopes added, but perhaps only enough of scope subtractions to ensure their uniqueness. So in the example I gave, I might shorten the subtractions to `-punctuation` and `-entity` respectively, as that is enough to ensure that those particular scopes have ended. I think doing it that way might improve readability. 

In any case, though, my view is that what a command like this would do is provide a good baseline from which to work. It is easy enough to remove test lines or tweak them after they are there, and this would let users avoid the grunt work of tracking down and entering the scope names and all the places on the line the scope set changes in the first place. 

Additionally, It would be a great way to quickly see what a syntax is doing on a line of code without having to inspect scopes all over the line.

**Comment by keith-hall** [comment]
I've recently been working on some keybindings to help with writing syntax tests, for my own use. (I got bored of constantly writing test files from scratch.)

If people would be interested, I could submit them as a PR to this repo, although maybe there will be a few things to consider first. Currently:

- when writing a test line, with a test line immediately above the current line, you can press <kbd>Tab</kbd> and it will put a `^` at the next column after the previous test ended. It might be useful to change this to "the next *non-whitespace* column after the previous test ended"
  - maybe as an option, in case we want it to create any clever assertions like `- keyword` after the `keyword` scope ends
- pressing <kbd>^</kbd> will automatically include more `^` characters where the scope of the line being tested is the same as the the scope of the character where you pressed the key
- both of the above also suggest a basic scope that will pass syntax tests, but selected so that you can press <kbd>^</kbd> again to extend the test to more columns - at which point, it will update the scope again so that it will still pass

Limitations:

- it currently doesn't deal with (/ insert) ending comment markers, if the language requires one, but I guess this could easily be added by checking if the comment marker used for tests has a comment end marker defined
- there might be times when you only want to test the last (space separated) scope, instead of all scopes that would succeed in a test. Currently it at least ignores the base scope of the file, but maybe it would be useful to configure it somehow / have a separate keybinding for it
- it currently doesn't deal with partial scopes very well i.e. `meta.function.python` + `meta.function.parameters.python` should become `meta.function` - at the moment it just considers them to not match

It's probably easier to see this in action than understand it from words:

![syntax test keybindings](https://cloud.githubusercontent.com/assets/11882719/21227817/1ba340a8-c2e4-11e6-8483-eadce0728a84.gif)

I know it's not the same as automatically generating all syntax tests, but maybe it would still be useful? What do you think? @jcberquist @FichteFoll

**Comment by jcberquist** [comment]
@keith-hall: I would love to see your code. I ended up creating a very basic version of what I was looking for, but what you have is a lot more targeted. I am very much not a Python expert but you can see what have here:

https://gist.github.com/jcberquist/0f9c3e551eb91c02a1990958dc3211db

As long as you are creating/sharing helpful commands...I would love to see a command that creates a highlight region on the line under test that matches  the area denoted by the `^` (one or many) on the current test line 😀 .

**Comment by keith-hall** [comment]
@jcberquist I just typed this up real quick, so it's probably a bit hacky:
https://gist.github.com/keith-hall/3499ef5b6ee68e22b45e5f05ab16cf2d

**Comment by jcberquist** [comment]
Thanks!

**Comment by FichteFoll** [comment]
That looks good, @keith-hall, and would definitely be a great addition. Please target a potential PR at the `develop` branch. I haven't tested this myself yet, however.

**Comment by keith-hall** [comment]
Will do, thanks @FichteFoll. Probably best not to look too closely at (testing) the gist I linked to, I'm rewriting it to be more robust and cleaner before I submit the PR :)

**Comment by jcberquist** [comment]
@FichteFoll: the additions contributed by @keith-hall are great; closing this request.
