### ISSUE TITLE
include directive unscoped

### ISSUE THREAD

**Issue by djspiewak** [SublimeText/PackageDev#81]
Is that intentional?  Specifically:  `source.yaml.sublime-syntax meta.block.contexts.sublime-syntax string.unquoted.plain.out.yaml entity.name.tag.yaml`, but nothing else.

**Comment by FichteFoll** [comment]
It is intentional, yes, but not final.

I tried to group keys into 4 families:

1. keys expecting a regular expression (`match` and `first_line_match`)
2. keys setting a scope named (basically everything with `scope` in it)
3. keys that affect the context flow (`set`, `push`, `pop`, `with_prototype`) or would be otherwise considered flow statements since they expect a mapping (`variables`, `contexts`, `captures`)
4. everything else

I'm not so confident about `captures` being in category 3 however. Imo it would also fit in 2.

**Comment by FichteFoll** [comment]
I changed some scope names for keys, including `include`, in b4413d60e06d0688f36fcdc31df6c91b05706d98. I'm still not happy with `entity.name.tag.yaml` being used, but as long as that is still in the default YAML syntax (which I won't change until https://github.com/sublimehq/Packages/pull/862 gets merged or decided on), we should be on solid ground.
